"""Fresh database initialization

Revision ID: 973679998edb
Revises: 
Create Date: 2025-09-16 10:23:28.270275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973679998edb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_code', sa.String(length=6), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verification_code', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.Column('date_reported', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user')
    # ### end Alembic commands ###
