"""Add phone fields to user table

Revision ID: aa44f2e184b9
Revises: 3805b07c4700
Create Date: 2025-09-13 02:08:59.516991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa44f2e184b9'
down_revision = '3805b07c4700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verification_code', sa.String(length=6), nullable=True))
        batch_op.create_unique_constraint('uq_user_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_phone', type_='unique')
        batch_op.drop_column('phone_verification_code')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('email_verification_code')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
